In [1]:
using Pkg
Pkg.add("MultivariateStats")
Pkg.add("CSV")
Pkg.add("DataFrames")


   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


In [24]:
using CSV, DataFrames,GLM

## Weight Gain

In [19]:
weightgain = CSV.read("/Users/VSR/Desktop/Capstone/ANOVA/weightgain.csv", DataFrame)

40×3 DataFrame
 Row │ source   type     weightgain 
     │ String7  String7  Int64      
─────┼──────────────────────────────
   1 │ Beef     Low              90
   2 │ Beef     Low              76
   3 │ Beef     Low              90
   4 │ Beef     Low              64
   5 │ Beef     Low              86
   6 │ Beef     Low              51
   7 │ Beef     Low              72
   8 │ Beef     Low              90
   9 │ Beef     Low              95
  10 │ Beef     Low              78
  11 │ Beef     High             73
  ⋮  │    ⋮        ⋮         ⋮
  31 │ Cereal   High             98
  32 │ Cereal   High             74
  33 │ Cereal   High             56
  34 │ Cereal   High            111
  35 │ Cereal   High             95
  36 │ Cereal   High             88
  37 │ Cereal   High             82
  38 │ Cereal   High             77
  39 │ Cereal   High             86
  40 │ Cereal   High             92
                     19 rows omitted

In [20]:
using Statistics

# Calculate mean
mean_stats = combine(groupby(weightgain, [:source, :type]), :weightgain => mean => :Mean)

# Calculate standard deviation
std_stats = combine(groupby(weightgain, [:source, :type]), :weightgain => std => :SD)

# Display results
println(mean_stats)
println(std_stats)


4×3 DataFrame
 Row │ source   type     Mean    
     │ String7  String7  Float64 
─────┼───────────────────────────
   1 │ Beef     Low         79.2
   2 │ Beef     High       100.0
   3 │ Cereal   Low         83.9
   4 │ Cereal   High        85.9
4×3 DataFrame
 Row │ source   type     SD      
     │ String7  String7  Float64 
─────┼───────────────────────────
   1 │ Beef     Low      13.8868
   2 │ Beef     High     15.1364
   3 │ Cereal   Low      15.7088
   4 │ Cereal   High     15.0218


In [21]:
using SimpleANOVA

# Perform two-way ANOVA with SimpleANOVA
anova_results = anova(weightgain, :weightgain, [:source, :type])

# Display the results
println(anova_results)



Analysis of Variance Results

       Effect       SS  DF        MS         F          p            ω²
-----------------------------------------------------------------------
        Total  10453.5  39                                             
         type   1299.6   1  1299.6    5.81231   0.0211449   0.107388   
       source    220.9   1   220.9    0.987949  0.326878   -0.000301355
type × source    883.6   1   883.6    3.9518    0.0544676   0.0687235  
        Error   8049.4  36   223.594                                   



## Foster

In [22]:

# Load the foster dataset (assuming it's saved as a CSV file)
foster = CSV.read("/Users/VSR/Desktop/Capstone/ANOVA/foster.csv", DataFrame)


61×3 DataFrame
 Row │ litgen   motgen   weight  
     │ String1  String1  Float64 
─────┼───────────────────────────
   1 │ A        A           61.5
   2 │ A        A           68.2
   3 │ A        A           64.0
   4 │ A        A           65.0
   5 │ A        A           59.7
   6 │ A        B           55.0
   7 │ A        B           42.0
   8 │ A        B           60.2
   9 │ A        I           52.5
  10 │ A        I           61.8
  11 │ A        I           49.5
  ⋮  │    ⋮        ⋮        ⋮
  52 │ J        B           52.8
  53 │ J        B           56.0
  54 │ J        I           45.2
  55 │ J        I           57.0
  56 │ J        I           61.4
  57 │ J        J           44.8
  58 │ J        J           51.5
  59 │ J        J           53.0
  60 │ J        J           42.0
  61 │ J        J           54.0
                  40 rows omitted

In [27]:
using GLM

using GLM

# Fit the two-way ANOVA model with interaction between litgen and motgen
foster_model = fit(LinearModel, @formula(weight ~ litgen * motgen), foster)


StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}

weight ~ 1 + litgen + motgen + litgen & motgen

Coefficients:
────────────────────────────────────────────────────────────────────────────────────
                           Coef.  Std. Error      t  Pr(>|t|)   Lower 95%  Upper 95%
────────────────────────────────────────────────────────────────────────────────────
(Intercept)             63.68        3.29364  19.33    <1e-22   57.0463    70.3137
litgen: B              -11.355       4.94046  -2.30    0.0262  -21.3056    -1.4044
litgen: I              -16.58        5.37849  -3.08    0.0035  -27.4128    -5.74716
litgen: J               -9.33        4.94046  -1.89    0.0654  -19.2806     0.620601
motgen: B              -11.28        5.37849  -2.10    0.0416  -22.1128    -0.447157
motgen: I               -9.555       4.94046  -1.93    0.0594  -19.5056     0.395601

In [29]:
# Compute the ANOVA table
foster_anova = anova(foster_model)




LoadError: MethodError: no method matching anova(::StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}})

Closest candidates are:
  anova(::DataFrame, ::Symbol, ::Vector{Symbol}, ::Vector{FactorType}; factornames)
   @ SimpleANOVA ~/.julia/packages/SimpleANOVA/lj0VA/src/anova_dataframes.jl:3
  anova(::DataFrame, ::Symbol, ::Vector{Symbol}; ...)
   @ SimpleANOVA ~/.julia/packages/SimpleANOVA/lj0VA/src/anova_dataframes.jl:3
  anova(::AbstractArray{T}, ::Vector{FactorType}; factornames, hasreplicates) where T<:Union{Number, AbstractVector{<:Number}}
   @ SimpleANOVA ~/.julia/packages/SimpleANOVA/lj0VA/src/anova.jl:98
  ...


## WATER

In [1]:

# Load the water dataset (assuming you saved it as a CSV file)
water = CSV.read("/Users/VSR/Desktop/Capstone/ANOVA/water.csv", DataFrame)


61×4 DataFrame
 Row │ location  town           mortality  hardness 
     │ String7   String15       Int64      Int64    
─────┼──────────────────────────────────────────────
   1 │ South     Bath                1247       105
   2 │ North     Birkenhead          1668        17
   3 │ South     Birmingham          1466         5
   4 │ North     Blackburn           1800        14
   5 │ North     Blackpool           1609        18
   6 │ North     Bolton              1558        10
   7 │ North     Bootle              1807        15
   8 │ South     Bournemouth         1299        78
   9 │ North     Bradford            1637        10
  10 │ South     Brighton            1359        84
  11 │ South     Bristol             1392        73
  ⋮  │    ⋮            ⋮            ⋮         ⋮
  52 │ North     Stockport           1557        13
  53 │ North     Stoke               1640        57
  54 │ North     Sunderland          1709        71
  55 │ South     Swansea             1625        13
  56 │ North     Wallasey            1625        20
  57 │ South     Walsall             1527        60
  58 │ South     West Bromwich       1627        53
  59 │ South     West Ham            1486       122
  60 │ South     Wolverhampton       1485        81
  61 │ North     York                1378        71
                                     40 rows omitted

In [3]:
using MultivariateStats, LinearAlgebra, CategoricalArrays

using Statistics

# Response matrix Y (dependent variables: hardness and mortality)
Y = Matrix(water[:, [:hardness, :mortality]])

# Encode location as dummy variables
water.location = categorical(water.location)
X = hcat(ones(nrow(water)), Matrix(water[:, [:location]]))



61×2 Matrix{Any}:
 1.0  String7("South")
 1.0  String7("North")
 1.0  String7("South")
 1.0  String7("North")
 1.0  String7("North")
 1.0  String7("North")
 1.0  String7("North")
 1.0  String7("South")
 1.0  String7("North")
 1.0  String7("South")
 1.0  String7("South")
 1.0  String7("North")
 1.0  String7("South")
 ⋮    
 1.0  String7("North")
 1.0  String7("North")
 1.0  String7("North")
 1.0  String7("North")
 1.0  String7("North")
 1.0  String7("South")
 1.0  String7("North")
 1.0  String7("South")
 1.0  String7("South")
 1.0  String7("South")
 1.0  String7("South")
 1.0  String7("North")

In [6]:
# Mean vector of Y
Y_bar = mean(Y, dims=1)

# Compute the total SSCP matrix
T = (Y .- Y_bar)' * (Y .- Y_bar)

# Compute the within-group SSCP matrix
groups = groupby(water, :location)
W = zeros(2, 2)
for g in groups
    Y_g = Matrix(g[:, [:hardness, :mortality]])
    Y_g_bar = mean(Y_g, dims=1)
    W += (Y_g .- Y_g_bar)' * (Y_g .- Y_g_bar)
end

# Between-group SSCP matrix
B = T - W


2×2 Matrix{Float64}:
 23122.0        -1.50817e5
    -1.50817e5   9.83729e5

In [8]:
using LinearAlgebra

# Ensure to use LinearAlgebra's eigvals function
eigvals_ = LinearAlgebra.eigvals

# Compute the Hotelling-Lawley trace
W_inv = inv(W)
eigvals_result = eigvals_(W_inv * B)  # Use the alias eigvals_
hotelling_lawley_trace = sum(eigvals_result)

println("Hotelling-Lawley Trace: ", hotelling_lawley_trace)


Hotelling-Lawley Trace: 0.9002148133569229


## Skulls

In [9]:
using CSV, DataFrames

# Load the skulls dataset
skulls = CSV.read("/Users/VSR/Desktop/Capstone/ANOVA/skulls.csv", DataFrame)


150×5 DataFrame
 Row │ epoch    mb     bh     bl     nh    
     │ String7  Int64  Int64  Int64  Int64 
─────┼─────────────────────────────────────
   1 │ c4000BC    131    138     89     49
   2 │ c4000BC    125    131     92     48
   3 │ c4000BC    131    132     99     50
   4 │ c4000BC    119    132     96     44
   5 │ c4000BC    136    143    100     54
   6 │ c4000BC    138    137     89     56
   7 │ c4000BC    139    130    108     48
   8 │ c4000BC    125    136     93     48
   9 │ c4000BC    131    134    102     51
  10 │ c4000BC    134    134     99     51
  11 │ c4000BC    129    138     95     50
  ⋮  │    ⋮       ⋮      ⋮      ⋮      ⋮
 141 │ cAD150     138    136     92     46
 142 │ cAD150     131    129     97     44
 143 │ cAD150     143    126     88     54
 144 │ cAD150     134    124     91     55
 145 │ cAD150     132    127     97     52
 146 │ cAD150     137    125     85     57
 147 │ cAD150     129    128     81     52
 148 │ cAD150     140    135    103     48
 149 │ cAD150     147    129     87     48
 150 │ cAD150     136    133     97     51
                           129 rows omitted

In [10]:
using Statistics

# Response matrix Y (dependent variables: mb, bh, bl, nh)
Y = Matrix(skulls[:, [:mb, :bh, :bl, :nh]])

# Encode epoch as categorical
skulls.epoch = categorical(skulls.epoch)
X = hcat(ones(nrow(skulls)), Matrix(skulls[:, [:epoch]]))


150×2 Matrix{Any}:
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 1.0  String7("c4000BC")
 ⋮    
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")
 1.0  String7("cAD150")

In [11]:
# Mean vector of Y
Y_bar = mean(Y, dims=1)

# Compute the total SSCP matrix
T = (Y .- Y_bar)' * (Y .- Y_bar)

# Compute the within-group SSCP matrix
groups = groupby(skulls, :epoch)
W = zeros(4, 4)  # There are 4 measurements: mb, bh, bl, nh
for g in groups
    Y_g = Matrix(g[:, [:mb, :bh, :bl, :nh]])
    Y_g_bar = mean(Y_g, dims=1)
    W += (Y_g .- Y_g_bar)' * (Y_g .- Y_g_bar)
end

# Between-group SSCP matrix
B = T - W


4×4 Matrix{Float64}:
  502.827  -228.147   -626.627   135.433
 -228.147   229.907    292.28    -66.0667
 -626.627   292.28     803.293  -180.733
  135.433   -66.0667  -180.733    61.2

In [12]:
using LinearAlgebra

# Compute the Hotelling-Lawley trace
W_inv = inv(W)
eigvals_ = LinearAlgebra.eigvals

# Compute the eigenvalues of W⁻¹B
eigvals_result = eigvals_(W_inv * B)

# Hotelling-Lawley trace is the sum of the eigenvalues
hotelling_lawley_trace = sum(eigvals_result)

println("Hotelling-Lawley Trace: ", hotelling_lawley_trace)


Hotelling-Lawley Trace: 0.48181907888097136


In [15]:
using LinearAlgebra

# Define trace function (sum of diagonal elements)
trace(M) = sum(diag(M))

# Compute the matrix (W + B)
W_plus_B = W + B

# Invert the (W + B) matrix
W_plus_B_inv = inv(W_plus_B)

# Compute the product (W + B)⁻¹ * B
product_matrix = W_plus_B_inv * B

# Compute Pillai's trace (sum of the diagonal elements)
pillai_trace = trace(product_matrix)

println("Pillai's Trace: ", pillai_trace)


Pillai's Trace: 0.3533055662224513


In [16]:
using LinearAlgebra

# Compute the total SSCP matrix (W + B)
W_plus_B = W + B

# Compute the determinant of W and (W + B)
det_W = det(W)
det_W_plus_B = det(W_plus_B)

# Compute Wilks' Lambda
wilks_lambda = det_W / det_W_plus_B

println("Wilks' Lambda: ", wilks_lambda)


Wilks' Lambda: 0.6635857985781096


In [17]:
using SimpleANOVA, DataFrames

# Perform ANOVA for each dependent variable (mb, bh, bl, nh)

# ANOVA for mb
anova_mb = anova(skulls, :mb, [:epoch])

# ANOVA for bh
anova_bh = anova(skulls, :bh, [:epoch])

# ANOVA for bl
anova_bl = anova(skulls, :bl, [:epoch])

# ANOVA for nh
anova_nh = anova(skulls, :nh, [:epoch])

# Display results
println("ANOVA for mb:")
println(anova_mb)
println("\nANOVA for bh:")
println(anova_bh)
println("\nANOVA for bl:")
println(anova_bl)
println("\nANOVA for nh:")
println(anova_nh)


ANOVA for mb:

Analysis of Variance Results

Effect        SS   DF        MS        F            p        ω²
---------------------------------------------------------------
 Total  3563.89   149                                          
 epoch   502.827    4  125.707   5.95461  0.000182632  0.116704
 Error  3061.07   145   21.1108                                


ANOVA for bh:

Analysis of Variance Results

Effect        SS   DF       MS        F          p         ω²
-------------------------------------------------------------
 Total  3635.17   149                                        
 epoch   229.907    4  57.4767  2.44742  0.0489699  0.0371634
 Error  3405.27   145  23.4846                               


ANOVA for bl:

Analysis of Variance Results

Effect        SS   DF        MS        F           p        ω²
--------------------------------------------------------------
 Total  4309.26   149                                         
 epoch   803.293    4  200.823   8.30566  